### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by mathiasbynens** [GoogleChromeLabs/jsvu#1]
The goal of this project is to support Mac, Linux, and Windows. I haven’t been able to test on Windows yet, however.

I suppose we’d have to use `Installer#installScript` to create batch files that run in `cmd.exe`.

Maybe @bterlson and @domenic have some input?

**Comment by bterlson** [comment]
Confirmed it does not work:

![image](https://user-images.githubusercontent.com/11236/33678225-fed1d634-da6f-11e7-9831-cfd262041b6e.png)

I usually avoid generating bash scripts for portability reasons and instead use pure JS (possibly with a shell helper like shelljs). Does this approach seem feasible? Otherwise yeah generating batch files will work. Not all windows people use Bash :)

**Comment by bterlson** [comment]
Ahh sorry, after updating my Node version from the super old 8.2 series, I get the following (likely more relevant) error:

![image](https://user-images.githubusercontent.com/11236/33679179-d73b7ba4-da72-11e7-8d33-4c94332ba447.png)

**Comment by mathiasbynens** [comment]
Apparently, [Windows does not allow creating symlinks without admin privileges](https://github.com/angular/angular-cli/issues/641#issuecomment-217548384) (i.e. without running `cmd.exe` as admin). Note to self: avoid symlinks in the Windows-specific installers.

**Comment by mathiasbynens** [comment]
@bterlson kindly shared another screenshot where symlinks are enabled by enabling Developer Mode:

![](https://user-images.githubusercontent.com/81942/33683454-40eebb6c-dacb-11e7-9991-96daf947a6e7.png)

It seems like on Windows, the DLLs really must be placed in the same directory.

**Comment by mathiasbynens** [comment]
@bterlson How did you get the non-ASCII characters to show up so nicely? I’m getting this:

![](https://user-images.githubusercontent.com/81942/33687720-44419524-dad9-11e7-9160-892c6992fc54.png)

**Comment by bterlson** [comment]
Yeah default console isn't so good at special characters. I use [Hyper](https://github.com/zeit/hyper) on Windows and it's great.

Reporting in that this now works on Windows provided you install AAS libs for JSC by either installing iTunes or by extracting the installer .msi using 7-zip or other archive utility (once extracted, look for AppleApplicationSupport.msi). Fwiw it seems like extracting the files from an MSI should be possible using the built-in msiexec but I haven't gotten that to work.

**Comment by mathiasbynens** [comment]
Thanks to @bterlson for letting me use his cloud VM so I could add Windows support! ♥

**Comment by bterlson** [comment]
@mathiasbynens happy to help, though you should get your own windows device for "testing" purposes ;)

Shall I jettison the VM now that things are working?

**Comment by mathiasbynens** [comment]
Yes, please feel free to reclaim the VM. :)
