### ISSUE TITLE
Unhandled promise rejection

### ISSUE THREAD

**Issue by CoderLim** [GoogleChromeLabs/jsvu#10]
![image](https://user-images.githubusercontent.com/13973117/33749488-f095b924-dc08-11e7-9631-613fbc5e3312.png)

What's the problem?

**Comment by mathiasbynens** [comment]
You’re using an old Node.js version. Didn’t npm give you a [warning](https://github.com/GoogleChromeLabs/jsvu/blob/0f058f4c335733bf1c52dae5eb70de6090676dd9/package.json#L14) when installing?

**Comment by mathiasbynens** [comment]
I’ve added an explicit note to the README now. Thanks for the report!

**Comment by karuppasamy** [comment]
Getting the same error again even after upgrading the nodeJs to v8.9.3.

```
$#  >node -v
v8.9.3

$#  >jsvu
📦 jsvu v1.0.5 — the JavaScript engine Version Updater 📦
✔ Read OS from config: mac64
✔ Read engines from config: chakra, javascriptcore, spidermonkey, v8
❯ Finding the latest Chakra version…
(node:78962) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'body' of undefined
(node:78962) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by mathiasbynens** [comment]
Looks like HTTP request fails… Can you please update to the latest `jsvu` version (`npm install jsvu -g`) and try again? Let me know what it logs.

**Comment by karuppasamy** [comment]
@mathiasbynens It's failed due the proxy settings (`http_proxy`, `https_proxy` in terminal). I made it success by disabling the proxy. Thanks for the response.
