### ISSUE TITLE
QuickJS now has win32, win64, linux32 and linux64 binaries

### ISSUE THREAD

**Issue by bellard** [GoogleChromeLabs/jsvu#101]

**Comment by mathiasbynens** [comment]
Thanks for the heads up! Will make the changes.

**Comment by muzinian** [comment]
@mathiasbynens  When I install quickjs in windows,I get error as follow:

> ✔ Found latest QuickJS version: v2021-03-27.
✔ URL: https://bellard.org/quickjs/binary_releases/quickjs-win-x86_64-2021-03-27.zip
✔ Download completed.
❯ Extracting…
✔ Extraction completed.
❯ Testing…
✖ Error: Command failed with exit code 2 (ENOENT): C:\Users\licheng/.jsvu/quickjs C:\Users\licheng\AppData\Local\Temp\7f89afc0c281b62e4f8fb296f5396916
spawn C:\Users\licheng/.jsvu/quickjs ENOENT

This error seem like `jsvu` not create `quickjs.cmd`. I have checked code in `quickjs/extract.js`,I find this code not use 'win64' in case statement, maybe this code is not correct?
https://github.com/GoogleChromeLabs/jsvu/blob/8d978c22a684f026548e4b5669b1ea1f38d2ad79/engines/quickjs/extract.js#L33-L37

**Comment by mathiasbynens** [comment]
@muzinian Could you send a patch? Thanks!

**Comment by muzinian** [comment]
@mathiasbynens I'm so sorry .I  can only read some javascript code.Sending a patch is beyond my power.

> @muzinian Could you send a patch? Thanks!

**Comment by liudonghua123** [comment]
The problem is the current code did not install correctly or completely. Maybe we can borrow some code from `xs`

https://github.com/GoogleChromeLabs/jsvu/blob/8d978c22a684f026548e4b5669b1ea1f38d2ad79/engines/quickjs/extract.js#L22-L41

https://github.com/GoogleChromeLabs/jsvu/blob/8d978c22a684f026548e4b5669b1ea1f38d2ad79/engines/xs/extract.js#L21-L51

**Comment by liudonghua123** [comment]
I changed some code, it seemed to work as expected.
![image](https://user-images.githubusercontent.com/2276718/134865671-bbf58795-1b25-4506-b955-ecbe60ed72b3.png)

**Comment by saghul** [comment]
@mathiasbynens I guess this one can be closed now.
