### ISSUE TITLE
JavaScriptCore cannot be downloaded (HTTPError: Response code 404 (Not Found))

### ISSUE THREAD

**Issue by mgol** [GoogleChromeLabs/jsvu#102]
When running latest `jsvu` (`1.12.0` right now) on macOS 10.15 with common engines added, I get the following:
```
$ jsvu                                                                  
📦 jsvu v1.12.0 — the JavaScript engine Version Updater 📦
✔ Read OS from config: mac64
✔ Read engines from config: chakra, hermes, javascriptcore, spidermonkey, v8, xs
✔ Found latest Chakra version: v1.11.23.
✖ Chakra v1.11.23 is already installed.
✔ Found latest Hermes version: v0.7.1.
✖ Hermes v0.7.1 is already installed.
❯ Finding the latest JavaScriptCore version…
✖ HTTPError: Response code 404 (Not Found)
✔ Found latest SpiderMonkey version: v83.0b10.
✖ SpiderMonkey v83.0b10 is already installed.
✔ Found latest V8 version: v8.8.294.
✖ V8 v8.8.294 is already installed.
✔ Found latest XS version: v10.4.0.
✖ XS v10.4.0 is already installed.
```
Note the `JavaScriptCore` part:
```
❯ Finding the latest JavaScriptCore version…
✖ HTTPError: Response code 404 (Not Found)
```

**Comment by mathiasbynens** [comment]
Looks like `https://build.webkit.org/builders/Apple%20Mojave%20Release%20%28Build%29?numbuilds=25` now 404s: https://github.com/GoogleChromeLabs/jsvu/blob/5f2df3ff476c65d676063326b0e7319ab2000060/engines/javascriptcore/get-latest-version.js#L39-L43

@msaboff @kmiller68 Any ideas on the new source of truth for the latest jsc version number?

**Comment by mathiasbynens** [comment]
Ah, looks like the URL format just changed slightly, with spaces becoming hyphens: `https://build.webkit.org/builders/Apple-Mojave-Release-Build?numbuilds=25`

**Comment by mathiasbynens** [comment]
Fix is available in `npm i -g jsvu@latest`!

**Comment by mgol** [comment]
Thank you! 🙂
