### ISSUE TITLE
JavaScriptCore: support upstream build.webkit.org updates

### ISSUE THREAD

**Issue by elinor-fung** [GoogleChromeLabs/jsvu#104]
On macOS Catalina 10.15.7 with jsvu 1.12.2:
```zsh
~ % jsvu --engines=javascriptcore
📦 jsvu v1.12.2 — the JavaScript engine Version Updater 📦
✔ Read OS from config: mac64
✔ Read engines from config: javascriptcore
❯ Finding the latest JavaScriptCore version…
✖ HTTPError: Response code 404 (Not Found)
```

Looks like https://build.webkit.org/builders/Apple-Mojave-Release-Build?numbuilds=1 returns 404 now (I don't see `Apple-Mojave-Release-Build` listed at https://build.webkit.org/builders/):
https://github.com/GoogleChromeLabs/jsvu/blob/f96a395d6655b9a471014ee89c1709a56bc8db54/engines/javascriptcore/get-latest-version.js#L40-L43

I locally changed `Mojave` -> `Catalina` in there and in `predict-url.js`, which worked for my purposes.

**Comment by mathiasbynens** [comment]
Looks like https://build.webkit.org/ changed to a new system recently (?).

Example ZIP URL:

```
https://s3-us-west-2.amazonaws.com/archives.webkit.org/mac-catalina-x86_64-release/272479.zip
```

**Comment by mathiasbynens** [comment]
Confirmed: https://lists.webkit.org/pipermail/webkit-dev/2021-February/031690.html

**Comment by mathiasbynens** [comment]
Here’s the steps to take for each builder, using [the `Apple-Win-10-Release-Build` builder](https://build.webkit.org/#/builders/67) (`builderid=67`) as an example.

1. Get the latest `buildid`:

    ```
    https://build.webkit.org/api/v2/builders/67/builds?order=-number&limit=1
    ````

    It’s `2737` in this case.

1. Get the `revision` for that `buildid` (in `buildsets[0].sourcestamps.revision`):

    ```
    https://build.webkit.org/api/v2/buildsets/2737
    ```

    It’s `272561` in this case.


1. This is enough to piece together the URL:

    ```
    https://s3-us-west-2.amazonaws.com/archives.webkit.org/win-x86_64-release/272569.zip
    ```

    To find the URL the first time (to figure out what to hardcode in jsvu), we can check the "transfer to s3" step on [the relevant build detail page](https://build.webkit.org/#/builders/67/builds/63), or alternatively fetch the logs based on the `buildid`:

    ```
    https://build.webkit.org/api/v2/logs/26027/contents
    ```
