### ISSUE TITLE
Test JSC on mac64arm

### ISSUE THREAD

**Issue by mathiasbynens** [GoogleChromeLabs/jsvu#107]
[I _think_ it should work](https://github.com/GoogleChromeLabs/jsvu/pull/106#discussion_r602470194), but I don't have an M1 Mac to test. @surma, could you take a look when you get a chance?

**Comment by surma** [comment]
it’s downloading _something_ with `arm64` in the name. But it’s ~500MB (🤯 ) and then it fails. I’ll investigate later

<img width="1598" alt="Screenshot 2021-03-26 at 23 10 29" src="https://user-images.githubusercontent.com/234957/112701413-7be16e80-8e88-11eb-8b9e-65072e80355e.png">
