### ISSUE TITLE
Issues with non-ASCII symbols in directory names on Windows

### ISSUE THREAD

**Issue by mathiasbynens** [GoogleChromeLabs/jsvu#11]
See <https://twitter.com/Bjorn_py/status/939648848724660226>:

> Mine is not working know why? Maybe the ö in my name messing up with the directory
> 
> ![](https://user-images.githubusercontent.com/81942/33800885-773fa592-dd4a-11e7-809c-8a42d05e938c.png)

**Comment by mathiasbynens** [comment]
Is there a way of getting the home directory in Windows in [8.3 format](https://support.microsoft.com/en-us/help/142982/how-windows-generates-8-3-file-names-from-long-file-names)?

I’ve asked Björn what `node -p 'require("os").homedir()'` (which is what `untildify` uses) returns for him.

**Comment by mathiasbynens** [comment]
It would also be interesting to check [`node -p 'require("os").tmpdir()'`](https://nodejs.org/api/os.html#os_os_tmpdir), as according to the above screenshot, that one gets it right.

**Comment by mathiasbynens** [comment]
Is there a way of getting the home directory in Windows in [8.3 format](https://support.microsoft.com/en-us/help/142982/how-windows-generates-8-3-file-names-from-long-file-names)?

I’ve asked Björn what [`node -p 'require("os").homedir()'`](https://nodejs.org/api/os.html#os_os_homedir) (which is what `untildify` uses) returns for him.

It would also be interesting to check [`node -p 'require("os").tmpdir()'`](https://nodejs.org/api/os.html#os_os_tmpdir), as according to the above screenshot, that one gets it right.

**Comment by mathiasbynens** [comment]
Is there a way of getting the home directory in Windows in [8.3 format](https://support.microsoft.com/en-us/help/142982/how-windows-generates-8-3-file-names-from-long-file-names)?

I’ve asked Björn what [`node -p 'require("os").homedir()'`](https://nodejs.org/api/os.html#os_os_homedir) (which is what `untildify` uses) returns for him.

It would also be interesting to check [`node -p 'require("os").tmpdir()'`](https://nodejs.org/api/os.html#os_os_tmpdir), as according to the above screenshot, that one gets it right. Or maybe that’s because of [the `fs.realpathSync()` call](https://nodejs.org/api/fs.html#fs_fs_realpathsync_path_options) in `tempy` through `temp-dir`? i.e.

```sh
node -p 'require("fs").realpathSync(require("os").homedir())'
```

**Comment by mathiasbynens** [comment]
![](https://user-images.githubusercontent.com/81942/33804604-b89bb0e0-dda8-11e7-8d9d-43bce06f51ff.png)

Just dusted off my old Windows 7 VM and tested this myself. `realpathSync` doesn’t help. My more surprising hypothesis of `tmpdir()` getting it right while `homedir()` doesn’t seems to be correct. 😨

**Comment by refack** [comment]
In reply to https://github.com/nodejs/node/issues/17586#issuecomment-350579889:
This seems to stem from a known limitation in `cmd.exe` that it doesn't understand Unicode (or UTF-8). 
There are various workarounds, but the most useful is to work with only relative paths, or env vars so:
```cmd
@echo off
%USERPROFILE%\foo.exe
```
will work, or:
```cmd
@echo off
%~dp0foo.exe
```
`%~dp0` being the directory `foo.cmd` is in.

Draft PR in #12

**Comment by silverwind** [comment]
Another idea would be to create a Powershell script (`.ps1`) and run that, thought the default execution policy might interfere.

**Comment by refack** [comment]
> Another idea would be to create a Powershell script (.ps1) and run that, thought the default execution policy might interfere.

We can wrap the call to `.ps1` in a `.cmd` file (bypass both execution policy and the fact that `.ps1` are not associated with powershell).
```cmd
powershell -NoProfile -ExecutionPolicy Unrestricted ".\foo.ps1" %*
```
