### ISSUE TITLE
Mac ARM jsshell looks available now

### ISSUE THREAD

**Issue by jkrems** [GoogleChromeLabs/jsvu#112]
It looks like jsshell is now building as a universal binary:

* Example URL: https://archive.mozilla.org/pub/firefox/releases/89.0b2/jsshell/
https://archive.mozilla.org/pub/firefox/releases/89.0b2/jsshell/jsshell-mac.zip

```console
$ file ~/Downloads/jsshell-mac/js
~/Downloads/jsshell-mac/js: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit executable x86_64] [arm64]
~/Downloads/jsshell-mac/js (for architecture x86_64):	Mach-O 64-bit executable x86_64
~/Downloads/jsshell-mac/js (for architecture arm64):	Mach-O 64-bit executable arm64
```

Which means it's likely enough to treat `mac64arm` the same as `mac64`?

**Comment by jkrems** [comment]
Checked that after added `mac64arm` to the switch statements in `spidermonkey/extract.js` and `spidermonkey/predict-url.js`, it looks like things are working:

```console
$ eshost -e 'Date.parse("1 Octopus 2018")'
#### JavaScriptCore
1538377200000

#### SpiderMonkey
NaN

#### V8
1538377200000
```

**Comment by mathiasbynens** [comment]
Nice! Do you want to submit a patch, @jkrems?
