### ISSUE TITLE
Bad $PATH instruction

### ISSUE THREAD

**Issue by rauchg** [GoogleChromeLabs/jsvu#116]
The README recommends adding `~/.jsvu` to the `$PATH`. If you look at its contents, however:

```
▲  ~/ ls ~/.jsvu
.               ..              engines         status.json     v8
```

you'll see that I get the `v8` binary (good!), but also I'm exposing `status.json` and `engines` to my `$PATH`

```
▲  ~/ engines
zsh: permission denied: engines
▲  ~/ status.json
zsh: permission denied: status.json
▲  ~/ v8
V8 version 9.6.56
d8> // nice!
```

Is there a reason for not putting `v8` above inside a `bin` subdirectory and instructing users to add `~/.jsvu/bin` to `$PATH`?

**Comment by mathiasbynens** [comment]
> Is there a reason for not putting `v8` above inside a `bin` subdirectory and instructing users to add `~/.jsvu/bin` to `$PATH`?

Not really. I agree it would be better. This would be a breaking change for people’s existing set-ups but we could give it a try. Patches welcome!
