### ISSUE TITLE
SHA-256 checksum: undefined

### ISSUE THREAD

**Issue by dilijev** [GoogleChromeLabs/jsvu#13]
On Windows, Node 9.2.0, jsvu v1.0.4:

```
✔ Found latest Chakra version: v1.7.5.
✔ URL: https://aka.ms/chakracore/cc_windows_all_1_7_5
✔ SHA-256 checksum: undefined
✔ Download and checksum verification completed.
```

Is `SHA-256 checksum: undefined` a bug?

**Comment by mathiasbynens** [comment]
Looks like GitHub changed its HTML output for pages such as https://github.com/Microsoft/ChakraCore/releases/tag/v1.7.5, adding `rel="nofollow"` to the download links. The regular expression at https://github.com/GoogleChromeLabs/jsvu/blob/bc4719922f8be03af4511442b80ab73f27864c29/engines/chakra/get-checksums.js#L21 wasn’t expecting this.

I’ll work around this for now, but a more robust fix would be for the Chakra team to host a `LATEST` file somewhere containing the version number of the latest release, or something similar. Would you be open to that?

**Comment by mathiasbynens** [comment]
Another bug was that if the checksum is not found, it’s set to `undefined`, causing it to be ignored. 

Since the downloads take place over HTTPS, the checksum verification is not really necessary — this doesn’t really impact security. Still, I’ve made jsvu throw an exception when it cannot find a checksum it was expecting to find.

**Comment by dilijev** [comment]
I'll discuss with the team whether we can host LATEST metadata on the master branch or something similar to help work around this problem. I think probably a LATEST.json file that has latest version number, links to the downloads and their corresponding checksums, rather than having JSVU rely on the release page.

**Comment by mathiasbynens** [comment]
Thank you! `LATEST.json` would be amazing.
