### ISSUE TITLE
v8.cmd file for Windows uses incorrect path

### ISSUE THREAD

**Issue by mthalman** [GoogleChromeLabs/jsvu#130]
I believe the changes in https://github.com/GoogleChromeLabs/jsvu/pull/123 caused an issue for Windows with jsvu 2.0.0. The contents of `.jsvu\bin\v8.cmd` are the following:

```
@echo off
"%~dp0engines/v8\v8.exe" --snapshot_blob="%~dp0engines/v8\snapshot_blob.bin" %*
```

When executing this file, it returns the error `The system cannot find the path specified.`. That's because `%~dp0` is resolving to the directory where the .cmd file is contained, which is now the bin directory. So it produces a path of ~\.jsvu\bin\engines\v8\v8.exe which is incorrect. I've verified this by moving the .cmd file up one directory and there it can execute correctly.

**Comment by mathiasbynens** [comment]
Can you try this?

```
@echo off
"%~dp0\..\engines/v8\v8.exe" --snapshot_blob="%~dp0engines/v8\snapshot_blob.bin" %*
```

**Comment by mathiasbynens** [comment]
If that works then the code change would be:

```diff
diff --git a/shared/installer.js b/shared/installer.js
index d27ebbe..79e43a7 100644
--- a/shared/installer.js
+++ b/shared/installer.js
@@ -132,7 +132,7 @@ class Installer {
 		const to = `${jsvuBinPath}/${name}`;
 		console.log(`Installing wrapper script to ${tildify(to)}…`);
 		const wrapperPath = process.platform === 'win32' ?
-			`%~dp0${this.targetRelPath}` :
+			`%~dp0..\${this.targetRelPath}` :
 			this.targetPath;
 		const contents = generateScript(wrapperPath)
 			.trimStart()
```

I’ll land a patch once you confirm/deny whether this does the trick, as I cannot test on Windows right now unfortunately.

**Comment by mthalman** [comment]
The same change needs to be applied to the snapshot path. This works:

```
"%~dp0\..\engines/v8\v8.exe" --snapshot_blob="%~dp0\..\engines/v8\snapshot_blob.bin" %*
```

**Comment by mathiasbynens** [comment]
Thanks @mthalman! Please check if jsvu@2.0.1 solves the issue.

**Comment by mthalman** [comment]
Yep, that fixed it for me. Thanks!

**Comment by mathiasbynens** [comment]
Yay! Thanks :)
