### ISSUE TITLE
s/QuickJS/QuickJS-NG/?

### ISSUE THREAD

**Issue by bnoordhuis** [GoogleChromeLabs/jsvu#141]
As upstream quickjs development seems to be pretty dead, @saghul and yours truly begun a friendly fork over at https://github.com/quickjs-ng/quickjs that's been picking up momentum.

Do I summarize correctly that the requirements for adding/replacing are as follows?

1. provide binaries at a stable location for:
  - i686 and x86_64 windows
  - i686 and x86_64 linux
  - arm64 macos

2. provide at a stable location a LATEST.json with `{"version":"x.y.z"}` - or can jsvu compute that from GH release tags?

3. PR jsvu with the new location?

**Comment by mathiasbynens** [comment]
Your summary is spot-on! A `LATEST.json` (or `.txt`) would be ideal but most projects unfortunately don’t provide this. In those cases we can consult the GitHub API, like here: https://github.com/GoogleChromeLabs/jsvu/blob/main/engines/xs/get-latest-version.js

**Comment by bnoordhuis** [comment]
Thanks for the quick reply, Mathias! I'll see if I can get GHA to produce a LATEST.json. Should I close this issue and PR when we're ready?

**Comment by mathiasbynens** [comment]
> Should I close this issue and PR when we're ready?

Sure, sounds good!
