### ISSUE TITLE
Enable installing specific engine versions alongside the auto-updated binary 

### ISSUE THREAD

**Issue by chicoxyzzy** [GoogleChromeLabs/jsvu#16]
It may be useful to compare results of different versions (not only latest). It'll be great to have version manager to be able to run such tests.

**Comment by mathiasbynens** [comment]
My gut reaction is that this is outside the scope of the jsvu project.

I could, _maybe_, be convinced to add a CLI flag to install a given version of a given JavaScript engine, e.g.:

```sh
jsvu --engine=v8 --version=6.6.50 # re-uses --os=… from the config
```

But I feel like the actual management of multiple versions should then be handled outside of jsvu, as part of another tool. WDYT?

**Comment by chicoxyzzy** [comment]
Yes, this is good option too.
