### ISSUE TITLE
invalid checksum for ChakraCore on 64-bit linux

### ISSUE THREAD

**Issue by michaelficarra** [GoogleChromeLabs/jsvu#17]
```
✔ Found latest Chakra version: v1.8.0.
✔ URL: https://aka.ms/chakracore/cc_linux_x64_1_8_0
✔ SHA-256 checksum: 76db2799c044de8aabb4dec565ff4d2e26055af272f6cb71ba490229c3fe2a16
❯ Downloading and verifying checksum…
✖ Invalid checksum. Expected: 76db2799c044de8aabb4dec565ff4d2e26055af272f6cb71ba490229c3fe2a16 Actual: a0bee34ba584f36b379012cc837a517a9fe365c21a0fccd4e1b7fa8df7a6c381
```

Manually fetching this file yields the same (actual) hash I see here.

**Comment by mathiasbynens** [comment]
I can confirm this:

```sh
wget https://aka.ms/chakracore/cc_linux_x64_1_8_0
sha256sum cc_linux_x64
```

https://github.com/Microsoft/ChakraCore/releases/tag/v1.8.0 says the SHA-256 checksum for the Linux archive is supposed to be `76db2799c044de8aabb4dec565ff4d2e26055af272f6cb71ba490229c3fe2a16`.

@dilijev @bterlson Does the GitHub page contain the wrong hash somehow, or is something terrible going on?

**Comment by dilijev** [comment]
@obastemur can you check the hash of the original file? Maybe there was an upload error?

**Comment by dilijev** [comment]
I confirmed on Windows the actual hash from the download is A0BEE34BA584F36B379012CC837A517A9FE365C21A0FCCD4E1B7FA8DF7A6C381

**Comment by dilijev** [comment]
The hashes of the other two archives in that release (Windows, OSX) match the expected hashes.

**Comment by mathiasbynens** [comment]
@dilijev Can you please update the hash on https://github.com/Microsoft/ChakraCore/releases/tag/v1.8.0?

I’m closing this issue as this is not a jsvu bug.

+@natashenka who also just ran into this.

**Comment by dilijev** [comment]
We have fixed the download. Expected hash remains the same.

**Comment by michaelficarra** [comment]
@dilijev Should I be concerned about the file I downloaded and ran earlier with the invalid hash? Is there an explanation for what happened?

**Comment by dilijev** [comment]
User error. We accidentally set the link to redirect to the 1.7.4 archive. (You'll notice the actual hash matches the version [here](https://github.com/Microsoft/ChakraCore/releases/tag/v1.7.4).)

The hash was correct for the 1.8.0 archive, and the link has now been fixed so that the correct archive is downloaded.

So basically you just got an older version of ChakraCore than you expected.

**Comment by michaelficarra** [comment]
❤️ Thanks.
