### ISSUE TITLE
Add XS (Moddable) support

### ISSUE THREAD

**Issue by mathiasbynens** [GoogleChromeLabs/jsvu#18]
I’d love to add support for Moddable/XS to jsvu!

1. Does [Moddable](https://github.com/Moddable-OpenSource/moddable) offer precompiled XS binaries somewhere?
1. Is there a way of getting the latest available version (e.g. a `LATEST` file)?

+@phoddie

**Comment by phoddie** [comment]
Adding Patrick and Michael Kellner from Moddable to help.

+@patrick-soquet
+@mkellner

**Comment by patrick-soquet** [comment]
Just created a pull request. And signed the CLA!
