### ISSUE TITLE
Empty engines list cause jsvu to exit without warnings

### ISSUE THREAD

**Issue by senthilp** [GoogleChromeLabs/jsvu#2]
https://github.com/GoogleChromeLabs/jsvu/blob/b203fc9010f28d66e03cdbdbac5e0296aed15d0c/cli.js#L118

When we run `jsvu` for the first time and do not choose any engines, the `~/.jsvu/status.json` file is created with an empty engine list.
```json
{
        "os": "mac64",
        "engines": []
}
```
The [clis.js](https://github.com/GoogleChromeLabs/jsvu/blob/master/cli.js#L118) file only checks if `status.engines === undefined` and not empty length. That causes `jsvu` to exit without any warnings or information. Changing to `status.engines === undefined || !status.engines.length` should probably fix it.

**Comment by mathiasbynens** [comment]
Also show a warning when no engines have been selected immediately after prompting.
