### ISSUE TITLE
Allow to select older versions of a runtime/debugger

### ISSUE THREAD

**Issue by thlorenz** [GoogleChromeLabs/jsvu#25]
Hey awesome tool, just installed v8 with it in about a few seconds vs 15 mins compiling :)

However I'm trying to compare different v8 versions (crankshaft vs. turbofan), so I'd like to define which version to checkout exactly.

At this point it only allows me to select chakra or v8 or so.

**Comment by thlorenz** [comment]
Not gonna file a new issue, but it'd be nice to select which kind of build as well, i.e. for perf tests you want release, but to get more info on `%DebugPrint` the `optdebug` build is more useful.

I like to have both in my environment, aliased to different names.

**Comment by mathiasbynens** [comment]
This came up before in https://github.com/GoogleChromeLabs/jsvu/issues/16#issuecomment-360019511.

However, there is another issue at play here:

> However I'm trying to compare different v8 versions (crankshaft vs. turbofan), so I'd like to define which version to checkout exactly.

We only started to offer precompiled V8 binary downloads after Crankshaft vs. TurboFan were already released. So even if explicit version support is added to jsvu, it would only work for versions that have an existing download.

The same applies for the other JavaScript engines.

**Comment by mathiasbynens** [comment]
Another problem:

> for perf tests you want release, but to get more info on %DebugPrint the optdebug build is more useful.

We (V8) currently don’t offer precompiled debug build binaries.

**Comment by thlorenz** [comment]
Ah ok, thanks for the quick answer. I'll keep a manually compiled crankshaft version around then and will once in a while build me a kinda up to date debug build to investigate :).

**Comment by mathiasbynens** [comment]
If such downloads ever become available, I’d be open to adding a `v8-debug` entry to jsvu. https://github.com/GoogleChromeLabs/jsvu/issues/19 is a similar case, for Chakra.
