### ISSUE TITLE
V8 debug binaries

### ISSUE THREAD

**Issue by vsemozhetbyt** [GoogleChromeLabs/jsvu#27]
Please consider a way to provide precompiled V8 debug binaries so that developers could use the full output of `%DebugPrint()` and other features.

**Comment by mathiasbynens** [comment]
Similar request for Chakra: #19

**Comment by mathiasbynens** [comment]
Some upstream progress: https://bugs.chromium.org/p/v8/issues/detail?id=5918#c72. There are still some upstream issues with the builder configuration for Windows and macOS, and for Linux there's https://bugs.chromium.org/p/chromium/issues/detail?id=874862.

**Comment by Drag13** [comment]
Hi, is there any progress on this?
