### ISSUE TITLE
Failing xs downloads

### ISSUE THREAD

**Issue by mathiasbynens** [GoogleChromeLabs/jsvu#28]
As [reported](https://twitter.com/apaprocki/status/976843818325741568) by @apaprocki, `xs` downloads are failing:

```
✔ Found latest XS version: v8.4.0.
✔ URL: https://github.com/Moddable-OpenSource/moddable-xst/releases/download/v8.4.0/xst-mac.zip
❯ Downloading…
  [========================================================================] 100%

✖ HTTPError: Response code 404 (Not Found)
```

Glancing over https://github.com/Moddable-OpenSource/moddable-xst/releases, it looks like the URL format for the recent v8.4.0 downloads is different than the agreed-upon format.

```
Expected: https://github.com/Moddable-OpenSource/moddable-xst/releases/download/v8.4.0/xst-mac.zip
Actual:   https://github.com/Moddable-OpenSource/moddable-xst/files/1824862/xst-mac.zip
```

@patrick-soquet can you please restore the expected URL format?

**Comment by apaprocki** [comment]
@mathiasbynens You beat me to it, sorry was afk :)

**Comment by mathiasbynens** [comment]
@apaprocki No worries :) Thanks for the report!

**Comment by patrick-soquet** [comment]
Oops. Wrong place to upload. It should be better now.

**Comment by mathiasbynens** [comment]
Thanks!
