### ISSUE TITLE
✖ TypeError: Cannot read property '1' of null

### ISSUE THREAD

**Issue by paulirish** [GoogleChromeLabs/jsvu#31]
![image](https://user-images.githubusercontent.com/39191/38634305-02d00a8e-3d77-11e8-9295-a0438fc017f7.png)

The regex didnt match.

Not necessarily because of ZA̡͊͠͝LGΌ, but because they don't use a compare link anymore.

**Comment by Jack-Works** [comment]
jsvu
📦 jsvu v1.13.4 — the JavaScript engine Version Updater 📦
✔ Read OS from config: win64
✔ Read engines from config: chakra, graaljs, hermes, javascriptcore, quickjs, spidermonkey, v8, xs
✔ Found latest Chakra version: v1.11.24.
✖ Chakra v1.11.24 is already installed.
❯ Finding the latest GraalJS version…
✖ TypeError: Cannot read properties of null (reading '1')
✔ Found latest Hermes version: v0.11.0.
✖ Hermes v0.11.0 is already installed.
✔ Found latest JavaScriptCore version: v254749.
✖ JavaScriptCore v254749 is already installed.
✔ Found latest QuickJS version: v2021-03-27.
✖ QuickJS v2021-03-27 is already installed.
✔ Found latest SpiderMonkey version: v106.0b2.
✖ SpiderMonkey v106.0b2 is already installed.
✔ Found latest V8 version: v10.8.35.
✖ V8 v10.8.35 is already installed.
❯ Finding the latest XS version…
✖ TypeError: Cannot read properties of null (reading '1')

Having this problem again on XS and GraalJS
