### ISSUE TITLE
V8 download for v6.7.288.5 is failing

### ISSUE THREAD

**Issue by mathiasbynens** [GoogleChromeLabs/jsvu#35]
For some reason <https://storage.googleapis.com/chromium-v8/official/canary/v8-mac64-rel-6.7.288.5.zip> doesn‘t work. As long as v6.7.288.5 is the first tag to appear on https://github.com/v8/v8/releases, V8 downloads through jsvu won’t work.

This problem will resolve itself once a new V8 tag is created.

A proper long-term solution would require a more reliable way of getting the latest V8 version number, ideally without having to implement V8’s weird version numbering details in jsvu. [A `LATEST.json` file for each architecture](https://bugs.chromium.org/p/v8/issues/detail?id=5918) would be helpful.

**Comment by mathiasbynens** [comment]
*Update:* I spoke to Michael Achenbach who was kind enough to write [a patch adding `LATEST.json` files for each architecture](https://chromium-review.googlesource.com/c/chromium/tools/build/+/1012103) that get updated whenever a new prebuilt download is published. These files will go live as soon as the V8 LKGR updates.

This change allows jsvu to get “the latest V8 version [for this architecture] [for which a download is available]” in a much more robust manner.

I have a jsvu patch ready to go, once I’ve gotten a chance to test it against the live files.

**Comment by stefanos1316** [comment]
Hello,

I am trying to install major released of v8 below 6 but I get a 403 HTTP message.
I am using jsvu v 1.7.1 and node version 11.13. 
The command is the following:

`jsvu v8@5.0.1`

Any clue on what I am doing wrong?

**Comment by mathiasbynens** [comment]
See <https://github.com/GoogleChromeLabs/jsvu#installing-specific-versions>:

> If you pass in an invalid version number, or if the JavaScript engine creators don’t provide a precompiled binary for that specific version, jsvu shows an error.

See https://docs.google.com/spreadsheets/d/1fVRDI45OTRwm7Ccta1SuId7aCzz1iDfTQw-ZCJEH5xA/edit for an overview of currently available V8 versions. We actually retro-actively compiled and uploaded several old versions, but not as far back as V8 v5.0.

**Comment by stefanos1316** [comment]
I see, thanks a lot for the info!

**Comment by mathiasbynens** [comment]
Btw, I would love to hear more about how you're using jsvu and your use case for having these old V8 versions. Feel free to shoot me an email at mths@google.com :) Thanks!

**Comment by stefanos1316** [comment]
Thanks a lot Mathias, it is mainly for research purpose and specifically for an idea I had. I will compose a mail soon enough and let you know! 

Kind regards,
Stefanos
