### ISSUE TITLE
[cli] `--engines` flag not respected

### ISSUE THREAD

**Issue by thlorenz** [GoogleChromeLabs/jsvu#37]
Even though I pass `--engines=v8` it still queries the engines I'd like to install.
I'd expect it to install v8 without asking instead.

```
> jsvu --engines=v8

📦 jsvu v1.1.4 — the JavaScript engine Version Updater 📦
? What is your operating system? macOS 64-bit
? Which JavaScript engines would you like to install? (Press <space> to select, <a> to to
ggle all, <i> to invert selection)
❯◉ Chakra/ChakraCore
 ◉ JavaScriptCore
 ◉ SpiderMonkey
 ◉ V8
 ◉ XS
```

**Comment by mathiasbynens** [comment]
[The CLI flags](https://github.com/GoogleChromeLabs/jsvu#integration-with-non-interactive-environments) only make sense for the CI use case, where you’d pass both `--engines` and `--os`. For every other use case, e.g. to manage installations on your development machine, you should just run `jsvu`. It persists your settings.

Do you have a different use case?

**Comment by mathiasbynens** [comment]
Just to be clear: I’m okay with patching this, but I also don’t want to encourage people from using these flags outside of CI environments. And outside of CI environments, the current behavior is okay, as you always pass both flags there.

**Comment by mathiasbynens** [comment]
@thlorenz Did you want to submit a patch for this one?

**Comment by thlorenz** [comment]
I will if I find some time :)
