### ISSUE TITLE
generate a d8.cmd as well

### ISSUE THREAD

**Issue by dilijev** [GoogleChromeLabs/jsvu#4]
Some people used to running the console hosts are used to calling the console host for v8, 'd8'

**Comment by mathiasbynens** [comment]
I’m opposed to this, as we’d then also have to add `js.cmd` for `SpiderMonkey`, and these names are confusing for anyone who hasn’t use the binaries directly IMHO. It’s easy enough to set up a symlink to `~/.jsvu/v8` or `~/.jsvu/spidermonkey` yourself if you’re used to invoking `d8` instead.

**Comment by dilijev** [comment]
Fair enough. I've done this for myself.
