### ISSUE TITLE
JSC could use WinCairo for Win64.

### ISSUE THREAD

**Issue by rkirsling** [GoogleChromeLabs/jsvu#43]
Hey @mathiasbynens! :wave: This is an awesome tool.

I noticed that Windows JSC is strictly using the 32-bit AppleWin port of WebKit (which depends on iTunes), but there's also a 64-bit WinCairo (i.e. non-Apple Windows) port, which my team works on. :smile:

Our documentation needs updating, but essentially you can skip the Apple-related dependencies and run `perl Tools\Scripts\build-webkit --wincairo` at the command prompt. There's also a [bot](https://build.webkit.org/builders/WinCairo%2064-bit%20WKL%20Release%20%28Build%29) producing full release builds (unfortunately no JSC-only build at present)—the output [here](https://build.webkit.org/builders/WinCairo%2064-bit%20WKL%20Release%20%28Build%29/builds/763/steps/transfer-to-s3/logs/stdio) gives an example.

Anyway, it would be cool to work with you to realize this!

**Comment by mathiasbynens** [comment]
Hey @rkirsling, great to see you here :) Thanks for the suggestion. Yeah, let’s do this!

I probably won’t get to this soon, so in case someone wants to contribute a patch for this: start in `engines/javascriptcore/*`.
