### ISSUE TITLE
jsc failing on windows

### ISSUE THREAD

**Issue by dilijev** [GoogleChromeLabs/jsvu#45]
Probably upstream but just in case this has to do with the way jsvu is unpacking jsc:

```
✔ Found latest JavaScriptCore version: v232897.
✔ URL: https://s3-us-west-2.amazonaws.com/archives.webkit.org/wincairo-x86_64-release/232897.zip
✔ Download completed.
❯ Extracting…
Installing library to ~\.jsvu\engines\javascriptcore\JavaScriptCore.resources\Info.plist…
Installing library to ~\.jsvu\engines\javascriptcore\DumpRenderTreeLib.dll…
Installing library to ~\.jsvu\engines\javascriptcore\JavaScriptCore.dll…
Installing library to ~\.jsvu\engines\javascriptcore\jscLib.dll…
Installing library to ~\.jsvu\engines\javascriptcore\libEGL.dll…
Installing library to ~\.jsvu\engines\javascriptcore\libGLESv2.dll…
Installing library to ~\.jsvu\engines\javascriptcore\MiniBrowserLib.dll…
Installing library to ~\.jsvu\engines\javascriptcore\testapiLib.dll…
Installing library to ~\.jsvu\engines\javascriptcore\testmasmLib.dll…
Installing library to ~\.jsvu\engines\javascriptcore\testRegExpLib.dll…
Installing library to ~\.jsvu\engines\javascriptcore\TestWebCoreLib.dll…
Installing library to ~\.jsvu\engines\javascriptcore\TestWebKitAPIInjectedBundle.dll…
Installing library to ~\.jsvu\engines\javascriptcore\TestWebKitLegacyLib.dll…
Installing library to ~\.jsvu\engines\javascriptcore\TestWebKitLib.dll…
Installing library to ~\.jsvu\engines\javascriptcore\TestWTFLib.dll…
Installing library to ~\.jsvu\engines\javascriptcore\WebKit.dll…
Installing library to ~\.jsvu\engines\javascriptcore\WebKit2.dll…
Installing library to ~\.jsvu\engines\javascriptcore\WTF.dll…
Installing library to ~\.jsvu\engines\javascriptcore\DumpRenderTree.pdb…
Installing library to ~\.jsvu\engines\javascriptcore\DumpRenderTreeLib.pdb…
Installing library to ~\.jsvu\engines\javascriptcore\ImageDiff.pdb…
Installing library to ~\.jsvu\engines\javascriptcore\JavaScriptCore.pdb…
Installing library to ~\.jsvu\engines\javascriptcore\jsc.pdb…
Installing library to ~\.jsvu\engines\javascriptcore\jscLib.pdb…
Installing library to ~\.jsvu\engines\javascriptcore\libEGL.pdb…
Installing library to ~\.jsvu\engines\javascriptcore\libGLESv2.pdb…
Installing library to ~\.jsvu\engines\javascriptcore\LLIntOffsetsExtractor.pdb…
Installing library to ~\.jsvu\engines\javascriptcore\MiniBrowser.pdb…
Installing library to ~\.jsvu\engines\javascriptcore\MiniBrowserLib.pdb…
Installing library to ~\.jsvu\engines\javascriptcore\testapi.pdb…
Installing library to ~\.jsvu\engines\javascriptcore\testapiLib.pdb…
Installing library to ~\.jsvu\engines\javascriptcore\testmasm.pdb…
Installing library to ~\.jsvu\engines\javascriptcore\testmasmLib.pdb…
Installing library to ~\.jsvu\engines\javascriptcore\testRegExp.pdb…
Installing library to ~\.jsvu\engines\javascriptcore\testRegExpLib.pdb…
Installing library to ~\.jsvu\engines\javascriptcore\TestWebCore.pdb…
Installing library to ~\.jsvu\engines\javascriptcore\TestWebCoreLib.pdb…
Installing library to ~\.jsvu\engines\javascriptcore\TestWebKit.pdb…
Installing library to ~\.jsvu\engines\javascriptcore\TestWebKitAPIInjectedBundle.pdb…
Installing library to ~\.jsvu\engines\javascriptcore\TestWebKitLegacy.pdb…
Installing library to ~\.jsvu\engines\javascriptcore\TestWebKitLegacyLib.pdb…
Installing library to ~\.jsvu\engines\javascriptcore\TestWebKitLib.pdb…
Installing library to ~\.jsvu\engines\javascriptcore\TestWTF.pdb…
Installing library to ~\.jsvu\engines\javascriptcore\TestWTFLib.pdb…
Installing library to ~\.jsvu\engines\javascriptcore\WebKit.pdb…
Installing library to ~\.jsvu\engines\javascriptcore\WebKit2.pdb…
Installing library to ~\.jsvu\engines\javascriptcore\WebKitNetworkProcess.pdb…
Installing library to ~\.jsvu\engines\javascriptcore\WebKitStorageProcess.pdb…
Installing library to ~\.jsvu\engines\javascriptcore\WebKitWebProcess.pdb…
Installing library to ~\.jsvu\engines\javascriptcore\WTF.pdb…
Installing binary to ~\.jsvu\engines\javascriptcore\jsc.exe…
Installing wrapper script to ~\.jsvu\javascriptcore.cmd…
✔ Extraction completed.
❯ Testing…
✖ Error: Command failed: C:\Users\doilij/.jsvu/javascriptcore C:\Users\doilij\AppData\Local\Temp\e6dbf97c188ee412a3409f98eac3e1d9
```

An error message pops up:

![image](https://user-images.githubusercontent.com/494055/41493850-a925e170-70c0-11e8-8be3-6d7819e9566f.png)

I'm confused because jscLib.dll is definitely extracted:

`Installing library to ~\.jsvu\engines\javascriptcore\jscLib.dll…`

And it's definitely there on disk and new. So it seems like maybe is somehow an invalid DLL?

**Comment by mathiasbynens** [comment]
@rkirsling, could you take a look please?

**Comment by rkirsling** [comment]
Sure, will look this week. :smile:

**Comment by rkirsling** [comment]
The issue here is that certain third-party DLLs (e.g. ICU) are needed to run `jsc.exe`, so we'll need to fetch and unzip a copy of [WinCairoRequirements](https://github.com/WebKitForWindows/WinCairoRequirements/releases) as well.

Sorry I missed this in #44—I had these DLLs in my path (and forgot that these are among the things that 32-bit AppleWin port references `Program Files\iTunes` for).

**Comment by rkirsling** [comment]
@mathiasbynens 
Any particular way you'd like to see this addressed? It appears that every existing step of `updateEngine` applies to all engines and platforms (at least potentially, even if checksum verification isn't actually used everywhere). Yet no other engine or platform needs external dependencies, nor should they in the future.

What I'd really like is for my team to handle this on the other side of the fence and provide a Win64 JSC build product that's runnable as-is, but I wouldn't be able to promise any sort of timeframe for this. 😞

**Comment by mathiasbynens** [comment]
How often do the `WinCairoRequirements` really change?

The ideal solution would be to include the `WinCairoRequirements` in the main ZIP file, especially if they change often. Should we revert #44 until this is done?

If they don't change that often, we could add a note to the README similar to the iTunes note telling people to install these dependencies manually... Although, where would the dependencies live? Would they need to be somewhere in `~/.jsvu`? (Sorry, no Windows device/VM to test here.)

**Comment by rkirsling** [comment]
Yeah, they don't change very often (only a few times per year); that's why the build doesn't include them.

(The WebKit build product is primarily used by test bots, so having to redownload the same 60 MB of DLLs for every build would be rather wasteful. On the other hand, if we had a JSC-only build, we could just bundle in the dependencies, since it requires very few of them—eventually it should be just ICU alone.)

They don't need to live under `~/.jsvu`, they just need to be on the user's path—I could absolutely add a note to the README about it. (We could add a more helpful error message too?)

**Comment by mathiasbynens** [comment]
> They don't need to live under `~/.jsvu`, they just need to be on the user's PATH—I could absolutely add a note to the README about it. (We could add a more helpful error message too?)

Sounds great — let’s do it!

Long-term, a JSC-only build would be lovely.

**Comment by dilijev** [comment]
Putting WinCairoRequirements\bin64 on my PATH solved the crash on my end.
