### ISSUE TITLE
V8 stable releases

### ISSUE THREAD

**Issue by tcare** [GoogleChromeLabs/jsvu#49]
I like to track stable vs. canary in various engines. V8 doesn't seem to always publish the .zip that matches the latest stable release on https://omahaproxy.appspot.com/.

Is there a reliable way to get these stable releases? Can we integrate this?

**Comment by mathiasbynens** [comment]
Now that the functionality to install a given version number is available, you could build this yourself on top of jsvu: https://github.com/GoogleChromeLabs/jsvu#installing-specific-versions

1. Get the version number (by getting it from omahaproxy, for example), e.g. `7.5.202`
1. Run `jsvu v8@7.5.202`
