### ISSUE TITLE
ARM support?

### ISSUE THREAD

**Issue by liorean** [GoogleChromeLabs/jsvu#50]
Right now jsvu is entirely limited to x86/x64 versions. It seems to me like ARM (32 & 64 bit) versions for at least linux and android would be desirable additions.

**Comment by mathiasbynens** [comment]
Which of [the supported engines](https://github.com/GoogleChromeLabs/jsvu#supported-engines) offer precompiled arm32 and arm64 binaries?

**Comment by frank-dspeed** [comment]
chakracore does - Windows 10 (ARM) & Windows 10 (ARM64)

**Comment by frank-dspeed** [comment]
@mathiasbynens what do you think about a engine build service i could create a repo that builds all engines for all platforms i can simply use github hooks to automate that.

**Comment by liorean** [comment]
Firefox nightlies contain Win64-Aarch64 builds. https://archive.mozilla.org/pub/firefox/nightly/latest-mozilla-central/

**Comment by mathiasbynens** [comment]
This was added a while back.
