### ISSUE TITLE
Latest JSC failing even with WinCairoRequirements installed

### ISSUE THREAD

**Issue by dilijev** [GoogleChromeLabs/jsvu#53]
Edit:
I've tried uninstalling/reinstalling the latest node, jsvu, eshost, iTunes, and WinCairoRequirements.

**Comment by rkirsling** [comment]
@dilijev Does pulling down the [latest release](https://github.com/WebKitForWindows/WinCairoRequirements/releases) help?

**Comment by dilijev** [comment]
Apologies for not posting more details. I meant to follow up with more details after I tried uninstalling/reinstalling the whole shebang (jsvu, eshost, WinCairoRequirements, iTunes). Nothing helped.

@mathiasbynens The error appears to be the same as if no WinCairoRequirements were in stalled (the generic error message)
@rkirsling Yes, I installed the latest WinCairoRequirements you linked before filing this issue.

**Comment by rkirsling** [comment]
Apparently in the [2018.10.09 release](https://github.com/WebKitForWindows/WinCairoRequirements/releases/tag/v2018.10.09) of WinCairoRequirements, the ICU DLLs changed from versioned filenames (e.g. `icudt61.dll`) to unversioned ones (e.g. `icudt.dll`), which means that the system32 DLLs of the same name will be prioritized over any that are specified in PATH.

We'll get a fix out as soon as we can, but in the meantime, a quick-and-dirty workaround is to shove the DLLs from `WinCairoRequirements\bin64` straight into `~\.jsvu\engines\javascriptcore`.

Sorry for the hassle and thanks for your patience! :bow:

**Comment by dilijev** [comment]
@rkirsling: That workaround worked for me, thanks!

**Comment by donny-dont** [comment]
@dilijev @mathiasbynens this should be fixed with the latest [WinCairoRequirements release](https://github.com/WebKitForWindows/WinCairoRequirements/releases/tag/v2019.02.07) and no longer require a workaround.

Please close after its verified 😺

**Comment by mathiasbynens** [comment]
@dilijev Could you please check if that solves the issue for you (after undoing the workaround)?

**Comment by dilijev** [comment]
Worked for me! (Removed the old installation folder of jsvu's copy of JavaScriptCore, and then installed the latest WinCairoRequirements, and then used jsvu to reinstall and tested all the engines under eshost.)
