### ISSUE TITLE
Maybe add `--help`

### ISSUE THREAD

**Issue by surma** [GoogleChromeLabs/jsvu#56]
Currently, `--help` just runs `jsvu` normally and tries to update engines. Some help message would be appreciated (how do I list my installed engines? How do I run them? etc etc)

**Comment by mathiasbynens** [comment]
This would be fairly simple to implement. The smallest possible change would be to add a `--help` / `-h` flag that just points to [the README](https://github.com/GoogleChromeLabs/jsvu#readme).

**Comment by fraxken** [comment]
I would be interested to help and talk about it :)

**Comment by mathiasbynens** [comment]
@fraxken Would you be interested in sending a PR that make `-h`/`--help` point to the README?

**Comment by fraxken** [comment]
yes ! I'm working on it tonight.

**Comment by fraxken** [comment]
Done here: https://github.com/GoogleChromeLabs/jsvu/pull/62

**Comment by mathiasbynens** [comment]
```
$ jsvu --help
📦 jsvu v1.8.2 — the JavaScript engine Version Updater 📦
[<engine>@<version>]
[--os={mac64,linux32,linux64,win32,win64}]
[--engines={chakra,hermes,javascriptcore,spidermonkey,v8,v8-debug,xs},…]

Complete documentation is online:
https://github.com/GoogleChromeLabs/jsvu#readme
```
