### ISSUE TITLE
ChakraCore v1.11.7 mac link has changed.

### ISSUE THREAD

**Issue by kjpou1** [GoogleChromeLabs/jsvu#63]
The link for mac osx Chakra has changed from "osx_x64" to "osx_64" for latest release.

So instead of `https://aka.ms/chakracore/cc_osx_x64_1_11_7` it is now `https://aka.ms/chakracore/cc_osx_64_1_11_7`

**Comment by mathiasbynens** [comment]
Thanks for the report, @kjpou1! I'll wait for a response on [my upstream comment](https://github.com/Microsoft/ChakraCore/issues/6034#issuecomment-472746938) before making any changes on the jsvu side. This really just seems like a publishing error. :(

**Comment by kjpou1** [comment]
This is now fixed upstream.
