### ISSUE TITLE
SpiderMonkey install broken

### ISSUE THREAD

**Issue by akoeplinger** [GoogleChromeLabs/jsvu#65]
The list at https://product-details.mozilla.org/1.0/firefox_history_development_releases.json seems to include `9.0b6` (from 2011) as the last entry now:

```
...
    "67.0b5": "2019-03-26",
    "67.0b6": "2019-03-29",
    "67.0b7": "2019-04-02",
    "7.0b1": "2011-08-18",
    "7.0b2": "2011-08-26",
    "7.0b4": "2011-09-06",
    "7.0b5": "2011-09-09",
    "7.0b6": "2011-09-19",
    "8.0b1": "2011-09-29",
    "8.0b2": "2011-10-10",
    "8.0b3": "2011-10-14",
    "8.0b4": "2011-10-21",
    "8.0b5": "2011-10-28",
    "8.0b6": "2011-11-03",
    "9.0b1": "2011-11-10",
    "9.0b2": "2011-11-17",
    "9.0b3": "2011-11-25",
    "9.0b4": "2011-12-02",
    "9.0b5": "2011-12-09",
    "9.0b6": "2011-12-15"
}
```

Looking at https://github.com/GoogleChromeLabs/jsvu/blob/master/engines/spidermonkey/get-latest-version.js and https://product-details.mozilla.org/1.0/firefox_versions.json it seems we could use the latter now as e.g. `LATEST_FIREFOX_DEVEL_VERSION` correctly points to `67.0b7` now.

/cc @mathiasbynens

**Comment by akoeplinger** [comment]
We filed https://bugzilla.mozilla.org/show_bug.cgi?id=1541636.

**Comment by mathiasbynens** [comment]
Alternatively, if we need to stick to `firefox_history_development_releases.json `:

```js
let latestVersion = 0;
let latestTimestamp = 0;
for (const [key, value] of Object.entries(o)) {
  const timestamp = +new Date(value);
  if (latestTimestamp < timestamp) {
    latestTimestamp = timestamp;
    latestVersion = key;
  }
}
console.log({ latestVersion, latestTimestamp });
```

I've pinged some Mozillians on IRC. Hopefully they'll be able to advise.

**Comment by mathiasbynens** [comment]
https://github.com/mozilla/release-services/commit/5b96b5b6ad5f04df53c819a77b923b0601692fbb fixed this upstream. Closing this issue. Thanks everyone!
