### ISSUE TITLE
Download complimenting headers too?

### ISSUE THREAD

**Issue by SoylentGraham** [GoogleChromeLabs/jsvu#66]
This project is a saviour for me (It's such a pain building JSC & v8), but it would be great to have the matching revision headers to go with the libraries that have been built.

Whilst the CI for the resources don't seem to have headers etc (understandably) we could grab them from github etc.
For the user, webkit for example, is something like a 40gb checkout, so grabbing 10kb of headers takes a bit longer than would be ideal.

It would be great to extend this project to grab headers from specific repositories with a sparse checkout (obviously user can do this, but automation is king) so things match up. (I'm sure we're all aware of the perils of a library with mismatched API calls)

**Comment by SoylentGraham** [comment]
This may be a moot point as for JSC at least, no binding `.lib` is in the outputs of the build, so the binaries alone cannot be used anyway... (currently writing a manual `LoadLibrary()` bridge)

The original point may stand regarding keeping declarations & definition aligned though :)

**Comment by mathiasbynens** [comment]
Hmm, I think this is out of scope for the jsvu project. You could automate this on top of jsvu if you want!

**Comment by SoylentGraham** [comment]
Fair enough, I didn't want to implement it, submit a PR and have it dismissed and then have to maintain a fork :)
This is the only repository that is even close to providing a usable library (built, can link with etc), but it's not quite enough for that as it currently stands (but even then 1000x easier than trying to get JSC to build)
