### ISSUE TITLE
Do not rely on sorting provided by Mozilla

### ISSUE THREAD

**Issue by rail** [GoogleChromeLabs/jsvu#67]
In [bug 1541636](https://bugzilla.mozilla.org/show_bug.cgi?id=1541636) we found that if we break the sorting of the Firefox releases, than jsvu doesn't  generate proper results. It'd be better to sort the objects using the dates, without relying on the JSON parser nor the original order.

**Comment by mathiasbynens** [comment]
Would Mozilla be open to providing [dedicated `latest.json` files](https://bugzilla.mozilla.org/show_bug.cgi?id=1541636#c3)?

If not, we’ll implement something like https://github.com/GoogleChromeLabs/jsvu/issues/65#issuecomment-479792811 as a workaround.

**Comment by rail** [comment]
Sounds like a great candidate for a "good first bug"!

BTW, for nightly builds we already have [something simlar](https://download.cdn.mozilla.net/pub/firefox/nightly/latest-mozilla-central/firefox-68.0a1.en-US.linux-x86_64.buildhub.json). You still need to get the latest version from [product details](https://github.com/mozilla-releng/product-details/blob/db26c40c417159e6e45bcf844d9e4975ddce5b92/public/1.0/firefox_versions.json#L6), but at least it doesn't require any new changes.
