### ISSUE TITLE
Prompt missing for the second time?

### ISSUE THREAD

**Issue by hemanth** [GoogleChromeLabs/jsvu#7]
<img width="429" alt="screen shot 2017-12-07 at 10 24 37 pm" src="https://user-images.githubusercontent.com/18315/33727264-84adfde0-db9d-11e7-9bb6-19fb2d2949fc.png">

^ I selected `v8` and installed it, the next time I ran `jsvu` I was expecting the prompt to install others.

<img width="404" alt="screen shot 2017-12-07 at 10 24 43 pm" src="https://user-images.githubusercontent.com/18315/33727281-89c289ea-db9d-11e7-8e1c-70c39076fd1e.png">

P.S: yet to read the source.

**Comment by mathiasbynens** [comment]
The idea is you select all the engines you want to manage through `jsvu` on the first run. It then goes and installs them for you. Later, you run `jsvu` again whenever you want to update them to the latest version.

You can `rm ~/.jsvu/status.json` to start over, or run `jsvu --os=mac64 engines=all` to enable installing all engines.

**Comment by hemanth** [comment]
Ended up with `rm ~/.jsvu/status.json`; 

`jsvu --os=mac64 engines=all` FTW!
