### ISSUE TITLE
Avoiding manual export

### ISSUE THREAD

**Issue by hemanth** [GoogleChromeLabs/jsvu#8]
`export PATH="${HOME}/.jsvu:${PATH}"` 

Was trying to find ways to avoid that step.

Had done something similar on [node-nightly](https://github.com/hemanth/node-nightly).

**Comment by mathiasbynens** [comment]
It’s not _really_ necessary — if you don’t want to modify your `PATH` you could just explicitly run e.g. `~/.jsvu/v8` every time.

An alternative could be to install aliases but that would require modifying the user’s dotfiles dynamically is something I’m not comfortable with (and would IMHO be worse than recommending to extend `PATH`).
