### ISSUE TITLE
jsvu vs xs 9.0.2

### ISSUE THREAD

**Issue by leobalter** [GoogleChromeLabs/jsvu#84]
Something is going wrong when I try to fetch xst with jsvu:

```
✔ Found latest XS version: v9.0.2.
✔ URL: https://github.com/Moddable-OpenSource/moddable-xst/releases/download/v9.0.2/xst-mac.zip
✔ Download completed.
❯ Extracting…
Installing binary to ~/.jsvu/engines/xs/xs…
Installing symlink at ~/.jsvu/xs pointing to ~/.jsvu/engines/xs/xs…
✔ Extraction completed.
❯ Testing…
✖ Error: Command failed with exit code 1 (EPERM): /Users/leo/.jsvu/xs -e print('Hi!');
```

```
➜  ~ xs -e print('Hi')
zsh: unknown file attribute: H

➜  ~ xs -e "print('Hi')"
TypeError: (host): C: xsCall: no function
```

I didn't have time to investigate the problem yet but I'm reporting here already.

cc @patrick-soquet

**Comment by patrick-soquet** [comment]
Thank you for the report. Only the -e option is broken. I forgot to test it because I never use it. Sorry. It will be fixed in the next release.

The -s and -m  options that you are using for test262 should work well.

**Comment by mgol** [comment]
@patrick-soquet This is still breaking running `jsvu` if you have XS installed. Any chance for a quick fix?

**Comment by patrick-soquet** [comment]
Sorry for the delay. xs 9.0.3 has been released to fix this issue

**Comment by mathiasbynens** [comment]
Actually, I'm still hitting the error even with xs v9.0.3:

```
✔ Found latest XS version: v9.0.3.
✔ URL: https://github.com/Moddable-OpenSource/moddable-xst/releases/download/v9.0.3/xst-lin64.zip
✔ Download completed.
❯ Extracting…
Installing binary to ~/.jsvu/engines/xs/xs…
Installing symlink at ~/.jsvu/xs pointing to ~/.jsvu/engines/xs/xs…
✔ Extraction completed.
❯ Testing…
✖ Error: Command failed with exit code 1 (EPERM): /usr/local/google/home/mathiasb/.jsvu/xs -e print('Hi!');
```

@patrick-soquet Have you verified the fix?

**Comment by patrick-soquet** [comment]
I had but then I uploaded the former version of the Linux builds. Sorry for that. I updated the release, it should be better.

**Comment by michaelficarra** [comment]
@mathiasbynens maybe it would be good to check that the output of a "version" flag contains the version we think we're installing?


```sh
$ ~/.jsvu/xs -v
XS 9.0.1
```

**Comment by mathiasbynens** [comment]
@michaelficarra I considered that originally, but ran into too many issues such as [`javascriptcore` not having a version flag](https://bugs.webkit.org/show_bug.cgi?id=167802) and `spidermonkey` outputting something like `JavaScript-C72.0` whereas the version identifier `jsvu` installs it from is `v72.0b8`.
