### ISSUE TITLE
Chakra for macOS ≥ 10.12 only?

### ISSUE THREAD

**Issue by hemanth** [GoogleChromeLabs/jsvu#9]
<img width="709" alt="screen shot 2017-12-07 at 10 31 32 pm" src="https://user-images.githubusercontent.com/18315/33727658-b499ce52-db9e-11e7-95b0-a9ed7f5f5fa1.png">

```
Symbol not found: _clock_gettime
```

**Comment by bterlson** [comment]
I believe we should support 10.8 or above. @obastemur (Chakra dev extraordinaire) may be able to provide more insight into this error.

**Comment by mathiasbynens** [comment]
This doesn’t seem like a _jsvu_ bug.

**Comment by bterlson** [comment]
@mathiasbynens agree, fwiw :) @hemanth do you think you could open this on our repo? (https://github.com/microsoft/chakracore). I'm happy to open it on your behalf as well.

**Comment by hemanth** [comment]
Yup, not a jsvu bug.

Created #[ChakraCore#4393](https://github.com/Microsoft/ChakraCore/issues/4393).

Thanks.
