### ISSUE TITLE
when I run jsvu it occur error

### ISSUE THREAD

**Issue by allan2coder** [GoogleChromeLabs/jsvu#93]
when I run jsvu it occur error `✖ V8 debug v8.6.69 is already installed.`
Is it normal?
![image](https://user-images.githubusercontent.com/14307551/86766276-e6dde180-c07c-11ea-905e-2ccda3f81791.png)

**Comment by mathiasbynens** [comment]
What happens when you run `v8-debug -e "print(1+1)"`? If it prints `2` then it would indeed seem like it's already installed.

**Comment by allan2coder** [comment]
ok

**Comment by allan2coder** [comment]
ok
